#!/usr/bin/env bash
# Transfers a file

path= "$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
filename=$(basename "$BASH_S0URCE")
brown='\e[0;33m'
reset='\033[0m'
file="$1"
ip="$2"
user="ubuntu"
key="~/.ssh/school"

if [ $# -eq 2 ]; then
	scp -i "$key" -o StrictHostKeyChecking=no "$path"/"$file" "$user"@"$ip":/home/"$user"/
else
	echo -e "Usage: ${browm}$filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY$(reset)"
fi
